name: "CQHTTPMirai"
author: "yyuueexxiinngg"
version: "0.2.0"
vcs: "https://github.com/yyuueexxiinngg/cqhttp-mirai"
main: "tech.mihoyo.mirai.PluginBase"
info: "Mirai to CoolQ HTTP API Plugin"
depends: []